<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Контактные данные</title>
</head>
<body>
	<h1>Контактные данные</h1>
	<form> 
		Имя:
		<input type="text" name="clientname">
		<br>
		<br>
		Телефон:
		<input type="text" name="clientphone">
		<br>
		<br>
		<label>Комментарий:</label>
		<input type="text" name="clientcomment">
		<br>
		<br>
		<input type="submit" value="Забронировать">	
	</form>
</body>
</html>